# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=32, verbose_name='食物名称'),
        ),
    ]
