# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者表', 'verbose_name_plural': '作者表'},
        ),
        migrations.AlterModelOptions(
            name='authordetail',
            options={'verbose_name': '作者详情表', 'verbose_name_plural': '作者详情表'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍表', 'verbose_name_plural': '书籍表'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name': '出版社表', 'verbose_name_plural': '出版社表'},
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(verbose_name='作者年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=32, verbose_name='作者姓名'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='addr',
            field=models.CharField(max_length=64, verbose_name='作者联系地址'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='birthday',
            field=models.DateField(verbose_name='作者出生日期'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='telephone',
            field=models.BigIntegerField(verbose_name='作者联系方式'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app01.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Publish', verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32, verbose_name='书籍名称'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='city',
            field=models.CharField(max_length=32, verbose_name='出版社所在城市'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='出版社邮箱'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='name',
            field=models.CharField(max_length=32, verbose_name='出版社名称'),
        ),
    ]
