# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180831_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='价格'),
        ),
    ]
