# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-05 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180831_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=1, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
